platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yusuga/Specs.git'

target 'YSImageRequestExample' do
  pod 'SDWebImage', '~> 3.0'
  pod 'NSString-Hash'
  pod 'YSImageFilter'#, :path => '~/code_public/YSImageFilter/'
  
  pod 'YSUIKitAdditions'
  pod 'M13ProgressSuite'

  target 'YSImageRequestExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
