source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yusuga/Specs.git'

platform :ios, '7.0'
pod 'SDWebImage'
pod 'NSString-Hash'
pod 'YSImageFilter'#, :path => '~/code_public/YSImageFilter/'

pod 'YSUIKitAdditions'
pod 'M13ProgressSuite'